
# Site settings
title: Stronger Trees
email: celeenrusk@gmail.com
description: "A Personal Development Blog"
baseurl: ""
url: "http://celeen.github.io/archive"

# Build settings
markdown: kramdown
permalink: pretty

#
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "post"
